import win32gui
import win32con
import win32api
import win32ui
import time
from PIL import Image
import cv2
import pyautogui as pag
import numpy as np
from matplotlib import pyplot as plt
import os
import multiprocessing as mp
import datetime
import ctypes
from ctypes import windll
import sys

_MAX_ITERATIONS = 10
sys.setrecursionlimit(10**8)

class ImageSearch:

    def __init__(self,PlayerName,Name):
        self.Name = Name
        self.PlayerName = PlayerName
        self.dir_path = os.path.dirname(os.path.abspath(__file__))
        self.hwnd = None
        self.hwnd_child = None
         
        
    def MainFrame_image_search(self):
        try:
            self.hwnd = win32gui.FindWindow(None,"{}".format(self.PlayerName))
            self.hwnd_child = win32gui.FindWindowEx(self.hwnd,0,0,"ScreenBoardClassWindow")
            left, top, right, bot = win32gui.GetWindowRect(self.hwnd)
            self.axis_main = [left,top,right,bot]
            w = self.axis_main[2] -self.axis_main[0]
            h = self.axis_main[3] - self.axis_main[1]
            hwndDC = win32gui.GetWindowDC(self.hwnd)
            mfcDC  = win32ui.CreateDCFromHandle(hwndDC)
            saveDC = mfcDC.CreateCompatibleDC()
            saveBitMap = win32ui.CreateBitmap()
            saveBitMap.CreateCompatibleBitmap(mfcDC, w, h)
            saveDC.SelectObject(saveBitMap)
            result = windll.user32.PrintWindow(self.hwnd, saveDC.GetSafeHdc(), 0)
            bmpinfo = saveBitMap.GetInfo()
            bmpstr = saveBitMap.GetBitmapBits(True)
            im = Image.frombuffer(
                'RGB',
                (bmpinfo['bmWidth'], bmpinfo['bmHeight']),
                bmpstr, 'raw', 'BGRX', 0, 1)
            win32gui.DeleteObject(saveBitMap.GetHandle())
            saveDC.DeleteDC()
            mfcDC.DeleteDC()
            win32gui.ReleaseDC(self.hwnd, hwndDC)
            if result == 1:
                im.save("{}\\img_Ref\\test_{}_{}.jpg".format(self.dir_path,self.PlayerName,self.Name))
            img1 = cv2.imread("{}\\img_Ref\\test_{}_{}.jpg".format(self.dir_path,self.PlayerName,self.Name),cv2.IMREAD_GRAYSCALE)
            temp= cv2.imread("{}\\img\\{}.jpg".format(self.dir_path,self.Name),cv2.IMREAD_GRAYSCALE)
            w,h = temp.shape[::-1]
            result = cv2.matchTemplate(img1,temp ,cv2.TM_CCOEFF_NORMED)
            minVal, maxVal, minLoc, maxLoc = cv2.minMaxLoc(result)
            top_left = maxLoc
            bottom_right = (top_left[0]+w,top_left[1]+h)
            cv2.rectangle(img1,top_left,bottom_right,255,2)
            self.X = round((top_left[0]+bottom_right[0])/2)
            self.Y = round((top_left[1]+bottom_right[1])/2)-30
            self.maxVal = maxVal
            return self.maxVal,self.X, self.Y
        except:
            self.MainFrame_image_search()


    def image_search_click(self,max_val,X,Y):
        while True:
            if max_val >= 0.7:
                now = datetime.datetime.now()
                f = open("{}\\Log\\log_{}{}{}.txt".format(self.dir_path,now.year,now.month,now.day),"a")
                print("{} {} {} {} {} {} : {}_{}를 클릭합니다.".format(now.year,now.month,now.day,now.hour,now.minute,now.second,self.PlayerName,self.Name),file=f)
                f.close()
                lParam = win32api.MAKELONG(X,Y)
                time.sleep(0.2)
                win32gui.SendMessage(self.hwnd_child, win32con.WM_LBUTTONDOWN, win32con.MK_LBUTTON, lParam)
                time.sleep(0.1)
                win32gui.SendMessage(self.hwnd_child, win32con.WM_LBUTTONUP, None, lParam)
                time.sleep(0.2)
                break
            else:
                now = datetime.datetime.now()
                f = open("{}\\Log\\log_{}{}{}.txt".format(self.dir_path,now.year,now.month,now.day),"a")
                print("{} {} {} {} {} {} : {}_{} 클릭을 실패했습니다.".format(now.year,now.month,now.day,now.hour,now.minute,now.second,self.PlayerName,self.Name),file=f)
                f.close()
                time.sleep(10)
                self.max_val,self.X,self.Y = self.MainFrame_image_search()
                self.image_search_click(self.max_val,self.X,self.Y)
                break

    def image_search_click_1(self,max_val,X,Y,time_1):
        while True:
            if max_val >= 0.7:
                now = datetime.datetime.now()
                f = open("{}\\Log\\log_{}{}{}.txt".format(self.dir_path,now.year,now.month,now.day),"a")
                print("{} {} {} {} {} {} : {}_{}를 클릭합니다.".format(now.year,now.month,now.day,now.hour,now.minute,now.second,self.PlayerName,self.Name),file=f)
                f.close()
                lParam = win32api.MAKELONG(X,Y)
                win32gui.SendMessage(self.hwnd_child, win32con.WM_LBUTTONDOWN, win32con.MK_LBUTTON, lParam)
                time.sleep(0.01)
                win32gui.SendMessage(self.hwnd_child, win32con.WM_LBUTTONUP, None, lParam)
                break
            else:
                now = datetime.datetime.now()
                f = open("{}\\Log\\log_{}{}{}.txt".format(self.dir_path,now.year,now.month,now.day),"a")
                print("{} {} {} {} {} {} : {}_{} 클릭을 실패했습니다.".format(now.year,now.month,now.day,now.hour,now.minute,now.second,self.PlayerName,self.Name),file=f)
                f.close()
                time.sleep(time_1)
                self.max_val,self.X,self.Y = self.MainFrame_image_search()
                self.image_search_click_1(self.max_val,self.X,self.Y,time_1)
                break
                
                

    def wheel_scroll(self,X,Y):
        SendMessage = ctypes.windll.user32.SendMessageW
        lParam = win32api.MAKELONG(X,Y)
        res1 = SendMessage(self.hwnd_child,win32con.WM_LBUTTONDOWN,win32con.MK_LBUTTON,lParam)
        for i in range(0,50,1):
            lParam = win32api.MAKELONG(X,Y-i)
            res2 = SendMessage(self.hwnd_child,win32con.WM_LBUTTONDOWN,win32con.MK_LBUTTON,lParam)
            time.sleep(0.001)
        res3 = SendMessage(self.hwnd_child,win32con.WM_LBUTTONUP,None,lParam)

def go_to_home():
    Dict_Player = [
        "NoxPlayer",
        "NoxPlayer(1)"
    ]
    Dict_item1 = [
    "Noran",
    "gotowhere"
    ]
    Dict_item2= [
        "ddeok",
    "sangjoem",
    "repair",
    "all_repair",
    "close",
    #"gotowhere2",
    ]
    #time.sleep(4)
    while True:
        now = datetime.datetime.now()
        endtime = now + datetime.timedelta(seconds=1800*4)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}_StartLog.txt".format(now.year,now.month,now.day),"a")
        print("본캐 Start Time : {}년 {}월 {}일 {}시 {}분" .format(now.year, now.month, now.day, now.hour, now.minute),
        "\n본캐 End Time : {}년 {}월 {}일 {}시 {}분" .format(endtime.year, endtime.month, endtime.day, endtime.hour, endtime.minute), file=f)
        f.close()
        time.sleep(1800*4)
        Fun2= ImageSearch("NoxPlayer","zeollist")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer","jeolchac")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer","Daejanggwan")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X+80,Y)        
        time.sleep(2)   
        Fun2= ImageSearch("NoxPlayer(1)","zeollist")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer(1)","jeolchac")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer(1)","Daejanggwan")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X+80,Y)        
        time.sleep(2)   
        func_gotostore = ImageSearch("NoxPlayer","ok")
        max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
        func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y)
        time.sleep(0.3)
        func_gotostore = ImageSearch("NoxPlayer(1)","ok")
        max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
        func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y)
        time.sleep(10)
        for j in Dict_item2:
            Fun1 = ImageSearch("NoxPlayer",j)
            max_val,X,Y = Fun1.MainFrame_image_search()
            Fun1.image_search_click(max_val,X,Y)
            time.sleep(0.5)
            Fun2 = ImageSearch("NoxPlayer(1)",j)
            max_val,X,Y = Fun2.MainFrame_image_search()
            Fun2.image_search_click(max_val,X,Y)
            time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","Doho")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","Doho")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","sohwanbisu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","sohwanbisu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","sinsu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(1)","sinsu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","chungryoung")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(1)","jujack")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        for i in range(1,50):
            func_gotostore = ImageSearch("NoxPlayer","health")
            max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
            func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y+10)
            time.sleep(0.2)
            func_gotostore2 = ImageSearch("NoxPlayer(1)","health")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10)   
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","close")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(1)","close")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer","zeollist")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer","jeolchac")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        Fun2= ImageSearch("NoxPlayer","Jode7")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X+80,Y)        
        time.sleep(2)   
        func_gotostore = ImageSearch("NoxPlayer","ok")
        max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
        func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y)
        time.sleep(4)
        func_gotostore = ImageSearch("NoxPlayer","sohwan")
        max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
        func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y)
        time.sleep(2)
        func_gotostore2 = ImageSearch("NoxPlayer(1)","surack")
        max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
        func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
        time.sleep(6)
        func_gotostore2 = ImageSearch("NoxPlayer(1)","DDara")
        max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
        func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
        time.sleep(1.5)
        func_gotostore2 = ImageSearch("NoxPlayer(1)","autokey")
        max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
        func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
        time.sleep(1.5)
        func_gotostore = ImageSearch("NoxPlayer","autokey")
        max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
        func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y)
def go_to_home_Sub():
    Dict_Player = [
        "NoxPlayer(2)",
        "NoxPlayer(3)"
    ]
    Dict_item1 = [
    "Noran",
    "gotowhere"
    ]
    Dict_item2= [
        "ddeok",
    "sangjoem",
    "repair",
    "all_repair",
    "close",
    #"gotowhere2",
    ]
    #time.sleep(4)
    while True:
        now = datetime.datetime.now()
        endtime = now + datetime.timedelta(seconds=1800*5)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}_StartLog.txt".format(now.year,now.month,now.day),"a")
        print("부캐 Start Time : {}년 {}월 {}일 {}시 {}분" .format(now.year, now.month, now.day, now.hour, now.minute),
        "\n부캐 End Time : {}년 {}월 {}일 {}시 {}분" .format(endtime.year, endtime.month, endtime.day, endtime.hour, endtime.minute), file=f)
        f.close()
        time.sleep(1800*5)  
        Fun1 = ImageSearch("NoxPlayer(2)","Doho")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(3)","Doho")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","sohwanbisu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(3)","sohwanbisu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","sinsu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(3)","sinsu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        for i in range(1,150):
            func_gotostore = ImageSearch("NoxPlayer(2)","health")
            max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
            func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y+10)
            time.sleep(0.2)
            func_gotostore2 = ImageSearch("NoxPlayer(3)","health")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10)   
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","close")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(3)","close")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    

def close_oneday_module1():
    while True:
        times = datetime.datetime.now()
        times_hour = int(times.hour)
        times_min = int(times.minute)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
        f.close()
        if times_hour == 0 and times_min >= 1 and times_min < 2:
            f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
            print(datetime.datetime.now()," : NOX에서 OnedayModule을 시작합니다.",file=f)
            f.close()
            time.sleep(3)
            func_gotostore2 = ImageSearch("NoxPlayer","onedayclose")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1)
            func_gotostore2 = ImageSearch("NoxPlayer(1)","onedayclose")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","onedayclose")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1)
            func_gotostore2 = ImageSearch("NoxPlayer(3)","onedayclose")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1)
            time.sleep(3)
            f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
            print(datetime.datetime.now()," : NOX에서 NextSuryung을 시작합니다.",file=f)
            f.close()
            func_gotostore2 = ImageSearch("NoxPlayer","Nextsuryung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            time.sleep(1)
            func_gotostore2 = ImageSearch("NoxPlayer(1)","Nextsuryung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","Nextsuryung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            time.sleep(1)
            func_gotostore2 = ImageSearch("NoxPlayer(3)","Nextsuryung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1200)
        else:
            time.sleep(10)

def close_event_module1():
    while True:
        times = datetime.datetime.now()
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
        print(datetime.datetime.now()," : 시작합니다. NoxPlayer Event Module 창 닫기를 시작합니다.",file=f)
        f.close()
        func_gotostore2 = ImageSearch("NoxPlayer","eventclose")
        max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
        func_gotostore2.image_search_click_1(max_val,gotostore2_X,gotostore2_Y,600)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
        print(datetime.datetime.now()," : 시작합니다. NoxPlayer(1) Event Module 창 닫기를 시작합니다.",file=f)
        f.close()
        func_gotostore2 = ImageSearch("NoxPlayer(1)","eventclose")
        max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
        func_gotostore2.image_search_click_1(max_val,gotostore2_X,gotostore2_Y,90)
        
def one_day_buy():
    while True:
        times = datetime.datetime.now()
        times_hour = int(times.hour)
        times_min = int(times.minute)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
        f.close()
        if times_hour == 7 and times_min >= 10 and times_min < 11:
            f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
            print(datetime.datetime.now()," : NOX에서 onedaybuy을 시작합니다.",file=f)
            f.close()
            func_gotostore2 = ImageSearch("NoxPlayer","gotoexpensivestore")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            func_gotostore2 = ImageSearch("NoxPlayer(1)","gotoexpensivestore")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","hwansu")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","hwansu")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","hwansumulpum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","hwansumulpum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","hwalryec")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","hwalryec")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","brammanmulsang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","brammanmulsang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","jaeryo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","jaeryo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","mugi")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","mugi")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","bangeo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","bangeo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","jangsin")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","jangsin")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","ilban")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","ilban")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","sungan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","sungan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            func_gotostore2 = ImageSearch("NoxPlayer","buhwal")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buhwal")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","Sungjang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","Sungjang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","Ujung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","Ujung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","Dohosohwan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","Dohosohwan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer","close_store")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(1)","close_store")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","gotoexpensivestore")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            func_gotostore2 = ImageSearch("NoxPlayer(3)","gotoexpensivestore")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","hwansu")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","hwansu")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","hwansumulpum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","hwansumulpum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","hwalryec")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","hwalryec")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","brammanmulsang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","brammanmulsang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","jaeryo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","jaeryo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","mugi")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","mugi")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","bangeo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","bangeo")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","jangsin")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","jangsin")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","ilban")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","ilban")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","sungan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","sungan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buhwal")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buhwal")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","Sungjang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","Sungjang")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","Ujung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","Ujung")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","Dohosohwan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","Dohosohwan")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","maximum")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","buy")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","storeOKbutton")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
            time.sleep(1.5)
            func_gotostore2 = ImageSearch("NoxPlayer(2)","close_store")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y) 
            func_gotostore2 = ImageSearch("NoxPlayer(3)","close_store")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
        else:
            time.sleep(10)

def go_to_home_Bobusang():
    while True:
        now = datetime.datetime.now()
        endtime = now + datetime.timedelta(seconds=1800*6)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}_StartLog.txt".format(now.year,now.month,now.day),"a")
        print("Start Time : {}년 {}월 {}일 {}시 {}분" .format(now.year, now.month, now.day, now.hour, now.minute),
        "\nEnd Time : {}년 {}월 {}일 {}시 {}분" .format(endtime.year, endtime.month, endtime.day, endtime.hour, endtime.minute), file=f)
        f.close()
        time.sleep(1800*6)
        Fun1 = ImageSearch("NoxPlayer","Premium")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","Premium")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","Bobusang")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","Bobusang")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","Sangjeomeyoung")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","Sangjeomeyoung")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","repair")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","repair")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","all_repair")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","all_repair")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","close")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","close")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","Doho")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","Doho")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","sohwanbisu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.2)
        Fun2 = ImageSearch("NoxPlayer(1)","sohwanbisu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","sinsu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(1)","sinsu")
        time.sleep(0.2)
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        time.sleep(3)
        for i in range(1,80):
            func_gotostore = ImageSearch("NoxPlayer","health")
            max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
            func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y+10)
            time.sleep(0.2)
            func_gotostore2 = ImageSearch("NoxPlayer(1)","Mana")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10)   
            time.sleep(0.2)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer","close")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(1)","close")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    

def go_to_home_Bobusang2():
    while True:
        now = datetime.datetime.now()
        endtime = now + datetime.timedelta(seconds=1800*5)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}_StartLog.txt".format(now.year,now.month,now.day),"a")
        print("부캐Start Time : {}년 {}월 {}일 {}시 {}분" .format(now.year, now.month, now.day, now.hour, now.minute),
        "\n부캐End Time : {}년 {}월 {}일 {}시 {}분" .format(endtime.year, endtime.month, endtime.day, endtime.hour, endtime.minute), file=f)
        f.close()
        time.sleep(1800*5)
        Fun1 = ImageSearch("NoxPlayer(2)","Premium")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","Premium")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","Bobusang")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","Bobusang")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","Sangjeomeyoung")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","Sangjeomeyoung")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","repair")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","repair")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","all_repair")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","all_repair")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","close")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","close")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","Doho")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","Doho")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","sohwanbisu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2 = ImageSearch("NoxPlayer(3)","sohwanbisu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","sinsu")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        time.sleep(0.5)
        Fun2= ImageSearch("NoxPlayer(3)","sinsu")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
        time.sleep(3)
        for i in range(1,110):
            func_gotostore = ImageSearch("NoxPlayer(2)","Mana")
            max_val,gotostore_X,gotostore_Y = func_gotostore.MainFrame_image_search()
            func_gotostore.image_search_click(max_val,gotostore_X,gotostore_Y+10)
            time.sleep(0.2)
            func_gotostore2 = ImageSearch("NoxPlayer(3)","Mana")
            max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
            func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y+10)   
            time.sleep(0.2)
        time.sleep(3)
        Fun1 = ImageSearch("NoxPlayer(2)","close")
        max_val,X,Y = Fun1.MainFrame_image_search()
        Fun1.image_search_click(max_val,X,Y)
        Fun2= ImageSearch("NoxPlayer(3)","close")
        max_val,X,Y = Fun2.MainFrame_image_search()
        Fun2.image_search_click(max_val,X,Y)    
def friendToCoin():
    while True:
        times = datetime.datetime.now()
        times_hour = int(times.hour)
        times_min = int(times.minute)
        f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
        f.close()
        if times_hour == 7 and times_min >=0  and times_min < 1:
            f = open("E:\\MyPython\\Macro\\Log\\log_{}{}{}.txt".format(times.year,times.month,times.day),"a")
            print(datetime.datetime.now()," : NOX에서 친구 보내기를 시작합니다.",file=f)
            f.close()
            Macro_list = ["NoxPlayer","NoxPlayer(1)","NoxPlayer(2)","NoxPlayer(3)"]
            friend_list = ["list","chingu","AllBonagie","FriendOKButton","FriendOKButton","friendclose"]
            for i in Macro_list:
                for j in friend_list:                  
                    func_gotostore2 = ImageSearch(i,j)
                    max_val,gotostore2_X,gotostore2_Y = func_gotostore2.MainFrame_image_search()
                    func_gotostore2.image_search_click(max_val,gotostore2_X,gotostore2_Y)
                    time.sleep(1.5)
            time.sleep(60)
        else:
            time.sleep(20)


import threading

if __name__ == "__main__":
    p1=mp.Process(target=go_to_home_Bobusang)
    p2=mp.Process(target=close_oneday_module1)
    p4=mp.Process(target=one_day_buy)
    p5=mp.Process(target=friendToCoin)
    p6=mp.Process(target=go_to_home_Bobusang2)
    processes = []
    processes.append(p1)
    processes.append(p2)
    processes.append(p4)
    processes.append(p5)
    processes.append(p6)
    for i in processes:
        i.start()
    for i in processes:
        i.join()